/**
 * Family Types & Interfaces
 * 
 * Defines the data structure for family sharing functionality.
 * This file creates the "blueprint" for how family data is structured in Firestore.
 */

/**
 * Family member roles - determines permissions
 * - admin: Can remove members, delete family, manage settings
 * - member: Can view and upload documents, but cannot manage family
 */
export type FamilyRole = 'admin' | 'member';

/**
 * FamilyMember Interface
 * Represents a single person in the family.
 * This is stored inside the Family document as an array.
 */
export interface FamilyMember {
  userId: string;           // Firebase Auth UID
  name: string;             // Display name (from user profile or email)
  email: string;            // User's email address
  role: FamilyRole;         // 'admin' or 'member'
  joinedAt: string;         // ISO date string (when they joined)
}

/**
 * Family Interface
 * Represents a complete family in Firestore.
 * Collection: 'families'
 * Document ID: Auto-generated by Firestore
 */
export interface Family {
  id: string;               // Firestore document ID
  name: string;             // Family name (e.g., "Smith Family")
  createdBy: string;        // userId of the person who created it
  members: FamilyMember[];  // Array of all family members
  inviteCode: string;       // 6-digit code for others to join (e.g., "123456")
  createdAt: string;        // ISO date string
  updatedAt: string;        // ISO date string (last modified)
}

/**
 * InviteCodeValidation
 * Result object when validating an invite code.
 * Used when someone tries to join a family.
 */
export interface InviteCodeValidation {
  isValid: boolean;         // true if code exists and is valid
  family?: Family;          // The family object (if valid)
  error?: string;           // Error message (if invalid)
}

/**
 * CreateFamilyInput
 * Data needed to create a new family
 */
export interface CreateFamilyInput {
  name: string;             // Family name from user input
  userId: string;           // Current user's ID (becomes admin)
  userName: string;         // Current user's display name
  userEmail: string;        // Current user's email
}

/**
 * JoinFamilyInput
 * Data needed to join an existing family
 */
export interface JoinFamilyInput {
  inviteCode: string;       // 6-digit code from another user
  userId: string;           // Current user's ID
  userName: string;         // Current user's display name
  userEmail: string;        // Current user's email
}

/**
 * UserProfile Interface
 * Extends your existing user data to include family information.
 * Collection: 'users'
 * Document ID: User's Firebase Auth UID
 */
export interface UserProfile {
  userId: string;           // Firebase Auth UID
  email: string;            // User's email
  name?: string;            // Display name (optional)
  familyId?: string | null; // Which family they belong to (null if none)
  familyRole?: FamilyRole;  // Their role in the family (undefined if not in family)
  createdAt: string;        // ISO date string
  updatedAt?: string;       // ISO date string
}

// ============================================
// HELPER FUNCTIONS
// ============================================

/**
 * Generate a random 6-digit invite code
 * Returns a string like "123456"
 */
export const generateInviteCode = (): string => {
  // Generates a number between 100000 and 999999
  return Math.floor(100000 + Math.random() * 900000).toString();
};

/**
 * Format invite code for display
 * "123456" → "123-456"
 * Makes it easier to read and type
 */
export const formatInviteCode = (code: string): string => {
  if (code.length !== 6) return code;
  return `${code.slice(0, 3)}-${code.slice(3)}`;
};

/**
 * Validate invite code format
 * Checks if input is exactly 6 digits (ignores hyphens/spaces)
 * Returns true for: "123456", "123-456", "123 456"
 * Returns false for: "12345", "abc123", etc.
 */
export const isValidInviteCodeFormat = (code: string): boolean => {
  const cleaned = code.replace(/[-\s]/g, ''); // Remove hyphens and spaces
  return /^\d{6}$/.test(cleaned); // Check if exactly 6 digits
};

/**
 * Clean invite code input
 * Removes hyphens and spaces from user input
 * "123-456" → "123456"
 */
export const cleanInviteCode = (code: string): string => {
  return code.replace(/[-\s]/g, '');
};